server {
  listen 80;
  server_name app.local-vbpool.nl;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name app.local-vbpool.nl;

  location / {
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;

    proxy_pass http://oauth2-proxy:4180;
  }

  ssl_certificate /etc/nginx/certs/_wildcard.local-vbpool.nl.pem;
  ssl_certificate_key /etc/nginx/certs/_wildcard.local-vbpool.nl-key.pem;
}
